### ISSUE TITLE
Getting the Javadoc requires username and password

### ISSUE THREAD

**Issue by Monniasza** [dhis2/grid#2]
I can't get the Javadoc, because a Jenkins login page shows up.
Publish the Javadoc on the website.

**Comment by larshelge** [comment]
Hi @Monniasza , thanks for your request. We haven't published the new Javadoc unfortunately.

If you are okay with it, you can clone the repository, generate the Javadoc with `mvn javadoc:javadoc` and view the Javadoc in directory `target/reports/apidocs/`.
